### ISSUE TITLE
No Hyper-V download option for Windows 10 VM

### ISSUE THREAD

**Issue by MichaelWeinberger** [MicrosoftEdge/dev.microsoftedge.com-vms#11]
**Steps to reproduce**

- go to: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/
The Hyper-V option for the Windows 10 VM image is gone. Win7 and Win81 are still available.

This issue was originally posted at: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/14991969/

**Comment by molant** [comment]
Closing in favor of #12
