### ISSUE TITLE
Mulitple VMs missing

### ISSUE THREAD

**Issue by balcsida** [MicrosoftEdge/dev.microsoftedge.com-vms#12]
![image](https://user-images.githubusercontent.com/1768446/34042357-9776e57c-e19c-11e7-85d6-ddf9d0897de6.png)

https://az412801.vo.msecnd.net/vhd/VMBuild_20141027/VMware/IE9/Windows/IE9.Win7.For.Windows.VMware.zip

**Comment by molant** [comment]
Thanks, we are aware and working on recovering those files.

**Comment by BogdanLivadariu** [comment]
same issue for IE11, win 8.1 for parallels

**Comment by molant** [comment]
We've recovered the VMs for VirtualBox.
The website list has now only the ones that are available and will be updated when we recover more of them.

Thanks for your patience

**Comment by molant** [comment]
New VMs added:

* VMWare IE11 Win8.1
* Parallels IE11 Win7

**Comment by molant** [comment]
This is the current status of the missing VMs.
I'll keep this table updated.


|             | HyperV | VBox  | VMware | Parallels |
| ------   | ------ | ----- | ------ | --------- |
| IE8 (Win 7)    |       |   X   |       |          |
| IE9 (Win 7)    |       |   X   |       |     X     |
| IE10 (Win 7)   |       |   X   |       |     X     |
| IE11 (Win 7)   |       |   X   |       |     X     |
| IE11 (Win 8.1)   |       |   X   |    X   |     X     |

**Comment by molant** [comment]
All Parallels machines should be back online

**Comment by balcsida** [comment]
Thank you, @molant ! :)

**Comment by molant** [comment]
IE8 to IE10 are now available for HyperV. Creating the remaining HyperV ones now.

VMWare will take a bit more, looks like VMWare Workstation 14 doesn't like my Xeon machine and need to find another one to create them :(

**Comment by jacek-dargiel** [comment]
Hey @molant Looks like the "MSEdge on Win10" for HyperV option links to the VMWare archive.

**Comment by molant** [comment]
Added missing HyperV for IE11

> Looks like the "MSEdge on Win10" for HyperV option links to the VMWare archive.

Thanks, I've removed it from the list for now. There's a problem with the system that generates the VMs, HyperV and the Falls creator update. After recovering all the VMs it's my next priority.

Sorry for the inconvenience.

**Comment by molant** [comment]
VirtualBox is done. Trying to figure out VMWare now

**Comment by molant** [comment]
VMWare is done. Looks like the only problem is VBox IE9

**Comment by molant** [comment]
Just finished creating the VirtualBox 9. All previous VMs should be restored. If there's any problem, please open an issue.
