### ISSUE TITLE
Hyper-V support

### ISSUE THREAD

**Issue by Falken1** [MicrosoftEdge/dev.microsoftedge.com-vms#13]
The Hyper-V VM selection for Win10 Microsoft edge, stable is actually a VMWare compatible VM.  Cannot find a Hyper_V compatible VM for WIN10 on the developer website.

**Comment by Falken1** [comment]
I just noticed that now the Hyper_V option is gone for that VM.

**Comment by alrra** [comment]
@Falken1 See: #12.

**Comment by Falken1** [comment]
It is a different issue as it was showing a Hyper-V option, but when downloaded it was actually a **10GB** VMWare  package

**Comment by molant** [comment]
@Falken1 see https://github.com/MicrosoftEdge/dev.microsoftedge.com-vms/issues/12#issuecomment-356637507 and the following comment
