### ISSUE TITLE
Some IE9 Win7 VMs actually have IE8

### ISSUE THREAD

**Issue by molant** [MicrosoftEdge/dev.microsoftedge.com-vms#16]
https://twitter.com/YupYoureRight/status/971056456718938112

**Comment by molant** [comment]
[Similar report but with HyperV](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/16306915/)

**Comment by alexangas** [comment]
Is there any way this issue might be able to get some love please @PatrickLang @molant ?

**Comment by molant** [comment]
I have other projects with higher priority  going and it's been challenging to get long periods of time to work on the vms because testing takes literally hours (and if it doesn't work you have to start again so...) 😔

That said, I might have some time in early August.

**Comment by Zenexer** [comment]
I'd be happy to contribute if possible.  As long as the README.md is up-to-date, I should be able to figure it out.

**Comment by HollyIT** [comment]
Just ran into this myself. For a simple workaround, you can download the IE9 standalone installed:

http://download.microsoft.com/download/C/3/B/C3BF2EF4-E764-430C-BDCE-479F2142FC81/IE9-Windows7-x86-enu.exe

I just did that and it works fine.

**Comment by JamesScript7** [comment]
Hey guys.. any timeframe on when this'll get any love?

**Comment by arjendevries** [comment]
@JamesScript7 , I had the same issue as you all.  So for the IE9 VM it has IE8.  Just pop the url @HollyIT  included above and I just ran it and it installed IE9 no problem.

**Comment by JamesScript7** [comment]
@arjendevries Thank you, I've decided to just use Browserstack. The IE8 browser in IE9 VM just hangs and crashes when I try to access that link...

**Comment by apokryfos** [comment]
If anyone has trouble installing the 32 bit IE on the 64bit windows VM then they can also try http://download.microsoft.com/download/C/1/6/C167B427-722E-4665-9A40-A37BC5222B0A/IE9-Windows7-x64-enu.exe

**Comment by JamesScript7** [comment]
haha, that makes a lot of sense, I'll give it one more try. ty @apokryfos

**Comment by brianjmiller** [comment]
Maybe if it isn't going to be fixed in a timely manner it can be removed as an option to prevent people wasting their time (and bandwidth for some) on downloading images that aren't going to work.

**Comment by molant** [comment]
Looks like the site has been updated and those VMs are no longer listed. Closing.

**Comment by Indigo744** [comment]
I don't know why this was closed, as the issue is not resolved:
![image](https://user-images.githubusercontent.com/7137528/113586466-d5d2f880-962d-11eb-9c75-37784e709e96.png)

I couldn't find any link to download a proper installer for IE9 (`IE9-Windows7-x64-enu.exe`). The link suggested by @apokryfos does not work, as MS has decided to remove it.
