### ISSUE TITLE
VMs appear out of date, Preview (15.15063) has no working download options

### ISSUE THREAD

**Issue by GregDomjan** [MicrosoftEdge/dev.microsoftedge.com-vms#6]
I was looking to test 
runtime.connectNative	Supported — Microsoft Edge (38) / Windows 10 (15002)

While the available list shows
Microsoft Edge on Win 10 Stable (14.14393)
Microsoft Edge on Win 10 Preview (15.15063)

The  Preview (15.15063) option doesn't allow selection of the VM type to activate a download button.

**Comment by molant** [comment]
Some people were having problems with the downloads but it should be fixed by now.
Let me know if it isn't the case.
