### ISSUE TITLE
MSEdge.Win10.RS2.Parallels.zip does not include Edge 15

### ISSUE THREAD

**Issue by chickenwing** [MicrosoftEdge/dev.microsoftedge.com-vms#9]
When choosing "MSEdge on Win10 (x64) Stable (15.15063)" for "Parallels (Mac)" on https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ the downloaded vm will not contain Edge 15 but only Edge 14.

**Comment by molant** [comment]
We are shipping now Edge 16 and soon 17. Let me know if you have problems with the newer VMs.
